"""Stage 1.5: emit recovered_pipeline.py from load-bearing + scaffolding cells."""
import os
import nbformat
from .classifier import classify_notebook


def recover_pipeline(nb_path: str) -> str:
    nb = nbformat.read(nb_path, as_version=4)
    records = classify_notebook(nb_path)

    out_lines = [
        f'"""Recovered production pipeline. Generated by CRUX from {nb_path}.',
        'Do not edit by hand - re-run `crux audit` to regenerate."""',
        "",
    ]

    for record, cell in zip(records, nb.cells):
        if record.classification not in ("load_bearing", "scaffolding"):
            continue
        if cell.cell_type != "code":
            continue
        out_lines.append(f"# --- {record.citation}: {record.classification} ({record.reason})")
        out_lines.append(cell.source.rstrip())
        out_lines.append("")

    return "\n".join(out_lines)


def write_recovered(nb_path: str, out_dir: str) -> str:
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "recovered_pipeline.py")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(recover_pipeline(nb_path))
    return out_path